
import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  Pressable,
  Image,
  Alert,
  Platform,
  Share,
} from 'react-native';
import { Stack, useRouter, useLocalSearchParams } from 'expo-router';
import { IconSymbol } from '@/components/IconSymbol';
import { colors } from '@/styles/commonStyles';
import { SafeAreaView } from 'react-native-safe-area-context';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as FileSystem from 'expo-file-system/legacy';

interface ProtectedItem {
  id: string;
  uri: string;
  type: 'image' | 'video';
  uploadDate: string;
  metadata: {
    size: number;
    width?: number;
    height?: number;
    duration?: number;
  };
  userIdentity: string;
}

export default function ProtectionReportScreen() {
  const router = useRouter();
  const { itemId } = useLocalSearchParams();
  const [item, setItem] = useState<ProtectedItem | null>(null);

  useEffect(() => {
    loadItem();
  }, [itemId]);

  const loadItem = async () => {
    try {
      const stored = await AsyncStorage.getItem('protected_items');
      if (stored) {
        const items: ProtectedItem[] = JSON.parse(stored);
        const foundItem = items.find(i => i.id === itemId);
        if (foundItem) {
          setItem(foundItem);
        }
      }
    } catch (error) {
      console.error('Error loading item:', error);
    }
  };

  const formatBytes = (bytes: number) => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return Math.round(bytes / Math.pow(k, i) * 100) / 100 + ' ' + sizes[i];
  };

  const formatDuration = (seconds?: number) => {
    if (!seconds) return 'N/A';
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  const handleShareAsText = async () => {
    if (!item) return;

    const reportText = `
🔒 SAVE ME - PROTECTION REPORT

Content Type: ${item.type === 'video' ? 'Video' : 'Image'}
Upload Date: ${new Date(item.uploadDate).toLocaleString()}
User Identity: ${item.userIdentity}

📊 Metadata:
- File Size: ${formatBytes(item.metadata.size)}
- Dimensions: ${item.metadata.width || 'N/A'} x ${item.metadata.height || 'N/A'}
${item.type === 'video' ? `- Duration: ${formatDuration(item.metadata.duration)}` : ''}

🛡️ Protection Status: ACTIVE
Encryption: AES-256
Auto-Delete: 24 hours after viewing
Screenshot Protection: ENABLED

Generated by Save Me - Your Privacy Guardian
    `.trim();

    try {
      await Share.share({
        message: reportText,
        title: 'Protection Report',
      });
    } catch (error) {
      console.error('Error sharing report:', error);
      Alert.alert('Error', 'Failed to share report');
    }
  };

  const handleShareAsImage = () => {
    Alert.alert(
      'Share as Image',
      'This feature will generate a visual protection report card. Coming soon!',
      [{ text: 'OK' }]
    );
  };

  const handleShareLink = () => {
    Alert.alert(
      'Share Link',
      'Cloud sharing with secure links will be available in the premium version.',
      [{ text: 'OK' }]
    );
  };

  if (!item) {
    return (
      <SafeAreaView style={[styles.container, { backgroundColor: colors.background }]}>
        <View style={styles.centerContent}>
          <Text style={styles.errorText}>Item not found</Text>
          <Pressable
            style={[styles.button, { backgroundColor: colors.primary }]}
            onPress={() => router.back()}
          >
            <Text style={styles.buttonText}>Go Back</Text>
          </Pressable>
        </View>
      </SafeAreaView>
    );
  }

  const reportSections = [
    {
      title: 'Content Information',
      icon: 'info.circle.fill',
      color: colors.primary,
      items: [
        { label: 'Content Type', value: item.type === 'video' ? 'Video' : 'Image' },
        { label: 'Upload Date', value: new Date(item.uploadDate).toLocaleString() },
        { label: 'User Identity', value: item.userIdentity },
      ],
    },
    {
      title: 'Technical Metadata',
      icon: 'chart.bar.fill',
      color: colors.secondary,
      items: [
        { label: 'File Size', value: formatBytes(item.metadata.size) },
        { label: 'Dimensions', value: `${item.metadata.width || 'N/A'} x ${item.metadata.height || 'N/A'}` },
        ...(item.type === 'video' ? [{ label: 'Duration', value: formatDuration(item.metadata.duration) }] : []),
      ],
    },
    {
      title: 'Protection Status',
      icon: 'shield.checkmark.fill',
      color: colors.success,
      items: [
        { label: 'Encryption', value: 'AES-256' },
        { label: 'Auto-Delete', value: '24 hours after viewing' },
        { label: 'Screenshot Protection', value: 'ENABLED' },
        { label: 'Status', value: 'ACTIVE' },
      ],
    },
  ];

  return (
    <>
      <Stack.Screen
        options={{
          title: 'Protection Report',
          headerBackTitle: 'Back',
        }}
      />
      <SafeAreaView style={[styles.container, { backgroundColor: colors.background }]} edges={['bottom']}>
        <ScrollView
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={false}
        >
          <View style={[styles.previewCard, { backgroundColor: colors.card }]}>
            <Image source={{ uri: item.uri }} style={styles.preview} />
            <View style={[styles.statusBadge, { backgroundColor: colors.success }]}>
              <IconSymbol name="checkmark.shield.fill" size={16} color="#ffffff" />
              <Text style={styles.statusBadgeText}>PROTECTED</Text>
            </View>
          </View>

          {reportSections.map((section, sectionIndex) => (
            <View key={sectionIndex} style={styles.section}>
              <View style={styles.sectionHeader}>
                <View style={[styles.sectionIcon, { backgroundColor: section.color }]}>
                  <IconSymbol name={section.icon} size={20} color="#ffffff" />
                </View>
                <Text style={styles.sectionTitle}>{section.title}</Text>
              </View>
              <View style={[styles.sectionCard, { backgroundColor: colors.card }]}>
                {section.items.map((item, itemIndex) => (
                  <React.Fragment key={itemIndex}>
                    <View style={styles.reportItem}>
                      <Text style={styles.reportLabel}>{item.label}</Text>
                      <Text style={styles.reportValue}>{item.value}</Text>
                    </View>
                    {itemIndex < section.items.length - 1 && <View style={styles.divider} />}
                  </React.Fragment>
                ))}
              </View>
            </View>
          ))}

          <View style={styles.section}>
            <Text style={styles.shareTitle}>Share Protection Report</Text>
            <View style={styles.shareButtons}>
              <Pressable
                style={[styles.shareButton, { backgroundColor: colors.primary }]}
                onPress={handleShareAsText}
              >
                <IconSymbol name="doc.text.fill" size={24} color="#ffffff" />
                <Text style={styles.shareButtonText}>As Text</Text>
              </Pressable>
              <Pressable
                style={[styles.shareButton, { backgroundColor: colors.secondary }]}
                onPress={handleShareAsImage}
              >
                <IconSymbol name="photo.fill" size={24} color="#ffffff" />
                <Text style={styles.shareButtonText}>As Image</Text>
              </Pressable>
              <Pressable
                style={[styles.shareButton, { backgroundColor: colors.accent }]}
                onPress={handleShareLink}
              >
                <IconSymbol name="link" size={24} color="#ffffff" />
                <Text style={styles.shareButtonText}>Share Link</Text>
              </Pressable>
            </View>
          </View>

          <View style={[styles.warningCard, { backgroundColor: colors.warning }]}>
            <IconSymbol name="exclamationmark.triangle.fill" size={24} color="#ffffff" />
            <View style={styles.warningContent}>
              <Text style={styles.warningTitle}>Important Notice</Text>
              <Text style={styles.warningText}>
                This content is protected and will auto-delete 24 hours after first viewing. 
                Screenshots and screen recording are blocked.
              </Text>
            </View>
          </View>
        </ScrollView>
      </SafeAreaView>
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingVertical: 20,
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  centerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    fontSize: 18,
    color: colors.textSecondary,
    marginBottom: 20,
  },
  button: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  previewCard: {
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 24,
    boxShadow: '0px 4px 12px rgba(0, 0, 0, 0.1)',
    elevation: 4,
  },
  preview: {
    width: '100%',
    height: 300,
    backgroundColor: colors.border,
  },
  statusBadge: {
    position: 'absolute',
    top: 16,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  statusBadgeText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
    marginLeft: 6,
  },
  section: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.text,
  },
  sectionCard: {
    borderRadius: 16,
    overflow: 'hidden',
    boxShadow: '0px 2px 6px rgba(0, 0, 0, 0.1)',
    elevation: 3,
  },
  reportItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
  },
  reportLabel: {
    fontSize: 14,
    color: colors.textSecondary,
    flex: 1,
  },
  reportValue: {
    fontSize: 14,
    color: colors.text,
    fontWeight: '600',
    flex: 1,
    textAlign: 'right',
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    marginLeft: 16,
  },
  shareTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 12,
  },
  shareButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  shareButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 16,
    borderRadius: 12,
    boxShadow: '0px 2px 6px rgba(0, 0, 0, 0.1)',
    elevation: 3,
  },
  shareButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 6,
  },
  warningCard: {
    flexDirection: 'row',
    padding: 16,
    borderRadius: 16,
    marginTop: 8,
  },
  warningContent: {
    flex: 1,
    marginLeft: 12,
  },
  warningTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: 4,
  },
  warningText: {
    fontSize: 13,
    color: '#ffffff',
    lineHeight: 18,
    opacity: 0.95,
  },
});
